### ISSUE TITLE
[BUG]-UdpServer causes app to shutdown ungracefully

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/PepperDashCore#102]
**Describe the bug**
When utilizing a the GenericUdpServer, whenever shutting down the application, the error log shows "app shut down ungracefully", due to a blocking thread.

**Comment by ndorin** [comment]
@jtalborough needs to weigh in on this.  There was a specific use case that caused the addition of the queue in this class.  We need to make sure that it's absolutely not needed before thinking it can be removed.
