### ISSUE TITLE
[FEATURE]-Add event to ICommunicationReceiver notifying change in IsConnected

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/PepperDashCore#132]
**Is your feature request related to a problem? Please describe.**
The ICommunicationReceiver interface requires a Connect(), Disconnect() and IsConnected{ get; } implementation.  It would make sense to implement an Event that notifies when IsConnected is updated.

**Describe the solution you'd like**
```csharp
public interface ICommunicationReceiver
{
  event EventHandler ConnectedStatusChanged;
}

public event EventHandler ConnectedStatusChanged;

protected virtual void OnConnectedStatusChanged()
{
  var handler = ConnectedStatusChanged;
  if (handler == null) return;

  handler(this, EventArgs.Empty);
}
```

**Describe alternatives you've considered**
Currently we cast to a GenericTcpIpClient to monitor the socket change.  Another alternative would be a separate interface with the event on it.

**Comment by andrew-welker** [comment]
The `ISocketStatus` interface has a `ConnectionChange` event on it. I would suggest casting to this interface instead of adding a second event on to the `ICommunicationReceiver` interface.

**Comment by ngenovese11** [comment]
OK, well what if the device is not a socket?  Ostensibly if it implements ICommunicationReceiver it has a Connect(), Disconnect(), and IsConnected property which would indicate that is has those statuses?

**Comment by ndorin** [comment]
> OK, well what if the device is not a socket? Ostensibly if it implements ICommunicationReceiver it has a Connect(), Disconnect(), and IsConnected property which would indicate that the IsConnected status might change?

That's what the `ICommunicationMonitor` interface is for.  It attaches to an `IBasicCommunication` class and monitors for the health of a non-socket (or socket) communication class by regularly sending a poll string and checking for a response.  It also has an `IsOnline` property and an `IsOnlineFeedback` property whose `OutputChange` event can be monitored.

It sounds like that should deliver what you need, no?

**Comment by ndorin** [comment]
Anything that isn't a socket (like a COM port or UDP server) doesn't have a positive feedback mechanism to drive connected status anyway.  We have to monitor the traffic to derive if we have a healthy communication stream.

**Comment by ngenovese11** [comment]
Got it, so the real problem is that the interface is too broad.  I'd agree we shouldn't pollute it any further.  In my case the ICommunicationMonitor  doesn't really do what I need since there's no poll string involved.  We connect, send the data, make sure we get the response we need, then disconnect.  It's a specialized device/situation though and I can use ISocketStatus to accomplish what's required.
